# Generated by Django 4.2.5 on 2023-09-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expenditure', 'Expenditure')], max_length=100),
        ),
    ]
